- name: Create application role
  oracle_role:
        hostname={{ inventory_hostname }}
        service_name={{ oracle_db.pdb }}
        user={{ user }}
        password={{ oracle_db.passwd }}
        role={{ item.name }}
        state={{ item.state }}
  environment: "{{oracle_env}}"
  with_items: "{{ roles }}"
  tags: role

- name: Add grants to role
  oracle_grants:
        hostname={{ inventory_hostname }}
        service_name={{ oracle_db.pdb }}
        user={{ user }}
        password={{ oracle_db.passwd }}
        role={{ item.name }}
        grants="{{ item.role_grants }}"
        state=present
  environment: "{{oracle_env}}"
  with_items:
         - "{{ roles }}"
  tags: role,grant
