---
# tasks file for host-config-asmlib

- name: Asmlib | Add configuration
  template: src=oracleasm.j2 dest=/etc/sysconfig/oracleasm-_dev_oracleasm
  register: asmlibconfig
  tags:
    - asmlib

- name: Asmlib | Add configuration (link)
  file: src=/etc/sysconfig/oracleasm-_dev_oracleasm dest=/etc/sysconfig/oracleasm state=link
  register: asmlibconfig
  tags:
    - asmlib

- name: Asmlib | Enable and start Oracle Asmlib
  service: name=oracleasm  state=started  enabled=yes
  tags:
    - asmlib

- name: Asmlib | Restart Asmlib
  service: name=oracleasm  state=restarted
  when: asmlibconfig.changed
  tags:
    - asmlib
