- hosts: sweoug
  become: true
  gather_facts: true
  # become: true
  vars:

     debug: false

     oracle_group:
       - dba
       - oinstall

     users:
        - { name: oracle, primarygroup: oinstall, othergroups: dba }


  tasks:


  - name: debug
    debug: var=oracle_group
    tags: debug
    when: debug

  - name: Create group
    group: name={{ item }} state=present
    with_items:
       - "{{ oracle_group }}"
    tags: group



  - name: Create user
    user: name={{ item.name }} group={{ item.primarygroup }} groups={{ item.othergroups }} state=present
    with_items:
       - "{{ users }}"
    tags: user

  - name: Create directory
    file: path=/u01 state=directory owner=oracle group=oinstall
    tags: directory
