- basename_vm: hroug
  num_vm: 1
  hostgroup: hroug
  domain: hroug.2017
  box: oravirt/ol74
  vagrant_user: vagrant
  vagrant_pass: vagrant
  ram: 4096
  cpu: 1
  base_pub_ip: 192.168.9.230
  synced_folders:
     #- {src: swrepo, dest: /media/swrepo}
     - {src: /home/miksan/Downloads/oracle, dest: /media/swrepo}
  base_disk_path:
  create_local_disk: true
  local_disks:
     - {name: u01, size: 75, count: 1}
     - {name: crs, size: 8, count: 3}
     - {name: data, size: 10, count: 3}
     - {name: fra, size: 20, count: 3}
  create_shared_disk: false
  provisioning:
  provisioning_env_override: false

