---
oracle_stage_directory: /u01/stage
oracle_base: /u01/app/oracle
oracle_home: "{{ oracle_base }}/product/{{ oracle_db.version }}/db"
oracle_home_gi: "{{ oracle_base }}/product/{{ oracle_gi.version }}/grid"
install_packages: False
user: system

oracle_gi:
      version: 12.2.0.1
      passwd: "{{ grid_passwd}}"

oracle_db:
      name: orcl
      passwd: "{{ oracle_passwd }}"
      version: 12.2.0.1
      cdb: true
      total_mb: 1024
      characterset: AL32UTF8
      ncharacterset: AL16UTF16
      datafile_dest: DATA
      recoveryfile_dest: DATA
      listener_name: LISTENER
      listener_protocols: TCP
      listener_port: 1521
      pdb: appdb1
      pdb_dg: '+APPDG'

oracle_groups:
     - oinstall
     - dba

oracle_user:
      name: oracle
      primgroup: oinstall
      dbagroup: dba
      othergroups: dba
      passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0"

oracle_env:
      ORACLE_HOME: "{{ oracle_home }}"
      LD_LIBRARY_PATH: "{{ oracle_home }}/lib"

filesystems:
 - fs: /u01
   vgname: vgora
   lvname: lvora
   device: /dev/sdb
   fstype: ext4
   lvsize: 100%FREE

crs_diskgroup: crs
asm_diskgroups:
 - diskgroup: crs
   state: present
   redundancy: external
   attributes:
     - {name: au_size, value: 1m}
     - {name: compatible.asm, value: 12.2.0.1.0}
     - {name: compatible.rdbms, value: 12.2.0.1.0}
   disk:
     - {device: /dev/sdc, asmlabel: crs01, asmdevice: 'ORCL:CRS01'}
     - {device: /dev/sdd, asmlabel: crs02, asmdevice: 'ORCL:CRS02'}
     - {device: /dev/sde, asmlabel: crs03, asmdevice: 'ORCL:CRS03'}
 - diskgroup: data
   state: present
   redundancy: external
   attributes:
     - {name: au_size, value: 4M}
     - {name: compatible.asm, value: 12.2.0.1.0}
     - {name: compatible.rdbms, value: 12.2.0.1.0}
   disk:
     - {device: /dev/sdf, asmlabel: data01, asmdevice: 'ORCL:DATA01'}
     - {device: /dev/sdg, asmlabel: data02, asmdevice: 'ORCL:DATA02'}
     - {device: /dev/sdh, asmlabel: data03, asmdevice: 'ORCL:DATA03'}
 - diskgroup: fra
   state: present
   redundancy: external
   attributes:
     - {name: au_size, value: 4M}
     - {name: compatible.asm, value: 12.2.0.1.0}
     - {name: compatible.rdbms, value: 12.2.0.1.0}
   disk:
     - {device: /dev/sdi, asmlabel: fra01, asmdevice: 'ORCL:FRA01'}
     - {device: /dev/sdj, asmlabel: fra02, asmdevice: 'ORCL:FRA02'}
     - {device: /dev/sdk, asmlabel: fra03, asmdevice: 'ORCL:FRA03'}
 # - diskgroup: APPDG
 #   state: present
 #   redundancy: external
 #   attributes:
 #     - {name: au_size, value: 4M}
 #     - {name: compatible.asm, value: 12.2.0.1.0}
 #     - {name: compatible.rdbms, value: 12.2.0.1.0}
 #   disk:
 #     - {device: /dev/sdl, asmlabel: appdg01, asmdevice: 'ORCL:APPDG01'}
 #     - {device: /dev/sdm, asmlabel: appdg02, asmdevice: 'ORCL:APPDG02'}
 #     - {device: /dev/sdn, asmlabel: appdg03, asmdevice: 'ORCL:APPDG03'}


services:
         - { name: "{{ oracle_db.pdb}}_service1", dbname: "{{ oracle_db.name }}", pdb: "{{ oracle_db.pdb }}", oracle_home: "{{ oracle_home }}", sn: "{{ oracle_db.pdb }}", state: present }
         - { name: appuser_service, dbname: "{{ oracle_db.name }}", pdb: "{{ oracle_db.pdb }}", oracle_home: "{{ oracle_home }}", sn: "{{ oracle_db.pdb }}", state: present }


init_parameters:
         #- { name: db_recovery_file_dest, value: /u01/fra, state: present, scope: both, sn: "{{ oracle_db.name}}" }
         - { name: db_recovery_file_dest_size, value: 10G, state: present, scope: both, sn: "{{ oracle_db.name}}" }
         - { name: db_recovery_file_dest, value: '+FRA', state: present, scope: both, sn: "{{ oracle_db.name}}" }
         - { name: db_create_file_dest, value: '+APPDG', state: present, scope: both, sn: "{{ oracle_db.pdb }}" }


tablespaces:
         - { name: appuser_data, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
         - { name: users, size: 5M, bigfile: false, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }


dba_user:
     - schema: dbauser
       schema_password_hash: B7C930D09B3AF263 # passwd = dbauser
       state: present
       default_tablespace: users
       default_temp_tablespace: temp
       grants:
            - dba

application_user:
     - schema: appuser
       schema_password: "{{ appuser_passwd}}" # appuser
       state: present
       default_tablespace: appuser_data
       default_temp_tablespace: temp
       grants:
            - approle1


roles:
     - name: approle1
       role_grants:
            - create session
            - create table
            - select any table
            - select any dictionary
       state: present
